### ISSUE TITLE
Double callback issue

### ISSUE THREAD

**Issue by Magnaboy** [enra4/crystalmethlabs#2]
```
const Crystalmethlabs = require('crystalmethlabs');
let osrs = new Crystalmethlabs('osrs');

osrs.stats('lynx titan', (err, stats) => {
	console.log(stats.ehp.hours); 
});
//OUTPUT
//15649.504780255
//15649.504780255
```
https://github.com/enra4/crystalmethlabs/blob/master/lib/async.js

**Comment by enra4** [comment]
hello. thanks for pointing this out. 

i fixed this small problem: https://github.com/enra4/crystalmethlabs/commit/bdc459f57d1cffcd885ea78651c6cc92448126e9#diff-e0233c812e19accfb7747914e3aa4d23

what i think the optimal fix for this is, is removing async.js and just using promises like any stable person would do. but since im retarded i wont be doing that. feel free to make a pull request
